const https = require('https');
const http = require('http');
const fs = require('fs');
const path = require('path');
const { execSync, spawn } = require('child_process');
const { runPreflight } = require('./preflight');

const JAR_URL = 'https://github.com/minima-global/Minima/raw/master/jar/minima.jar';

function followRedirects(url, callback) {
  const proto = url.startsWith('https') ? https : http;
  proto.get(url, { headers: { 'User-Agent': 'minima-installer' } }, (res) => {
    if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
      followRedirects(res.headers.location, callback);
    } else {
      callback(null, res);
    }
  }).on('error', (err) => callback(err));
}

function downloadJar(destDir, onProgress) {
  return new Promise((resolve, reject) => {
    fs.mkdirSync(destDir, { recursive: true });
    const destPath = path.join(destDir, 'minima.jar');

    followRedirects(JAR_URL, (err, res) => {
      if (err) return reject(err);
      if (res.statusCode !== 200) {
        return reject(new Error(`Download failed with status ${res.statusCode}`));
      }

      const totalBytes = parseInt(res.headers['content-length'], 10) || 0;
      let downloadedBytes = 0;
      const file = fs.createWriteStream(destPath);

      res.on('data', (chunk) => {
        downloadedBytes += chunk.length;
        if (totalBytes > 0 && onProgress) {
          onProgress(Math.round((downloadedBytes / totalBytes) * 100), downloadedBytes, totalBytes);
        }
      });

      res.pipe(file);

      file.on('finish', () => {
        file.close();
        resolve(destPath);
      });

      file.on('error', (err) => {
        fs.unlink(destPath, () => {});
        reject(err);
      });
    });
  });
}

function generateStartScript(config, installDir) {
  const preflight = runPreflight();
  const javaPath = preflight.java.path || 'java';
  const tmuxPath = preflight.tmux.path || 'tmux';
  const jarPath = path.join(installDir, 'minima.jar');

  let args = [`-jar "${jarPath}"`];

  if (config.port && config.port !== '9001') args.push(`-port ${config.port}`);
  if (config.dataFolder && config.dataFolder !== '~/.minima') args.push(`-data ${config.dataFolder}`);
  if (config.mdsEnable !== false) args.push('-mdsenable');
  if (config.mdsPassword) args.push(`-mdspassword "${config.mdsPassword}"`);
  if (config.rpcEnable) args.push('-rpcenable');
  if (config.rpcPassword) args.push(`-rpcpassword "${config.rpcPassword}"`);
  if (config.desktopMode !== false) args.push('-desktop');
  if (config.noP2P) args.push('-nop2p');
  if (config.connectNode) args.push(`-connect ${config.connectNode}`);
  if (config.dbPassword) args.push(`-dbpassword "${config.dbPassword}"`);
  if (config.archiveMode) args.push('-archive');
  if (config.megaMMR) args.push('-megammr');

  const javaCmd = `"${javaPath}" ${args.join(' ')}`;

  const script = `#!/bin/bash
# Minima Node Start Script
# Generated by minima-installer

JAVA="${javaPath}"
TMUX="${tmuxPath}"
JAR="${jarPath}"
SESSION="minima"

# Check if session already exists
if "$TMUX" has-session -t "$SESSION" 2>/dev/null; then
  echo "Minima is already running in tmux session '$SESSION'"
  echo "Run: tmux attach -t $SESSION"
  exit 0
fi

# Start Minima in a new tmux session
"$TMUX" new-session -d -s "$SESSION" '${javaCmd}'

echo "Minima started in tmux session '$SESSION'"
echo "To view: tmux attach -t $SESSION"
echo "To detach: press Ctrl+B then D"
`;

  const scriptPath = path.join(installDir, 'start-minima.sh');
  fs.writeFileSync(scriptPath, script, { mode: 0o755 });
  return { scriptPath, javaCmd };
}

function generateStopScript(installDir) {
  const preflight = runPreflight();
  const tmuxPath = preflight.tmux.path || 'tmux';

  const script = `#!/bin/bash
# Minima Node Stop Script
# Generated by minima-installer

TMUX="${tmuxPath}"
SESSION="minima"

if ! "$TMUX" has-session -t "$SESSION" 2>/dev/null; then
  echo "No Minima session found."
  exit 0
fi

# Send quit command to Minima
"$TMUX" send-keys -t "$SESSION" "quit" Enter

echo "Sent quit command to Minima."
echo "Waiting for graceful shutdown..."
sleep 3

# Check if still running
if "$TMUX" has-session -t "$SESSION" 2>/dev/null; then
  echo "Session still active. Killing tmux session..."
  "$TMUX" kill-session -t "$SESSION"
fi

echo "Minima stopped."
`;

  const scriptPath = path.join(installDir, 'stop-minima.sh');
  fs.writeFileSync(scriptPath, script, { mode: 0o755 });
  return scriptPath;
}

function generateLaunchAgent(installDir) {
  const startScript = path.join(installDir, 'start-minima.sh');
  const logPath = path.join(installDir, 'minima-launcher.log');

  const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.minima.node</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>${startScript}</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>StandardOutPath</key>
  <string>${logPath}</string>
  <key>StandardErrorPath</key>
  <string>${logPath}</string>
</dict>
</plist>`;

  const plistDir = path.join(process.env.HOME, 'Library', 'LaunchAgents');
  fs.mkdirSync(plistDir, { recursive: true });
  const plistPath = path.join(plistDir, 'com.minima.node.plist');
  fs.writeFileSync(plistPath, plist);
  return plistPath;
}

function launchTmuxSession(installDir) {
  const startScript = path.join(installDir, 'start-minima.sh');
  try {
    execSync(`bash "${startScript}"`, { encoding: 'utf8' });
    return true;
  } catch (err) {
    throw new Error(`Failed to start tmux session: ${err.message}`);
  }
}

async function install(config, sendEvent) {
  const homeDir = process.env.HOME;
  const installDir = path.join(homeDir, 'minima-installer');

  sendEvent('status', 'Preparing installation directory...');
  fs.mkdirSync(installDir, { recursive: true });

  sendEvent('status', 'Downloading minima.jar from GitHub...');
  const jarPath = await downloadJar(installDir, (percent, downloaded, total) => {
    const mb = (downloaded / 1024 / 1024).toFixed(1);
    const totalMb = (total / 1024 / 1024).toFixed(1);
    sendEvent('progress', JSON.stringify({ percent, downloaded: mb, total: totalMb }));
  });
  sendEvent('status', 'Download complete.');

  sendEvent('status', 'Generating start script...');
  const { scriptPath, javaCmd } = generateStartScript(config, installDir);

  sendEvent('status', 'Generating stop script...');
  const stopScript = generateStopScript(installDir);

  let plistPath = null;
  if (config.autoStart) {
    sendEvent('status', 'Setting up auto-start on login...');
    plistPath = generateLaunchAgent(installDir);
  }

  sendEvent('status', 'Starting Minima in tmux session...');
  launchTmuxSession(installDir);

  const mdsPort = (parseInt(config.port) || 9001) + 2;

  sendEvent('complete', JSON.stringify({
    installDir,
    jarPath,
    startScript: scriptPath,
    stopScript,
    plistPath,
    javaCmd,
    mdsPort,
    tmuxSession: 'minima'
  }));
}

module.exports = { install };
