const https = require('https');
const http = require('http');
const fs = require('fs');
const path = require('path');
const os = require('os');
const { execSync, spawn } = require('child_process');
const { runPreflight, isWindows } = require('./preflight');

const JAR_URL = 'https://github.com/minima-global/Minima/raw/master/jar/minima.jar';

function followRedirects(url, callback) {
  const proto = url.startsWith('https') ? https : http;
  proto.get(url, { headers: { 'User-Agent': 'minima-installer' } }, (res) => {
    if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
      followRedirects(res.headers.location, callback);
    } else {
      callback(null, res);
    }
  }).on('error', (err) => callback(err));
}

function downloadJar(destDir, onProgress) {
  return new Promise((resolve, reject) => {
    fs.mkdirSync(destDir, { recursive: true });
    const destPath = path.join(destDir, 'minima.jar');

    followRedirects(JAR_URL, (err, res) => {
      if (err) return reject(err);
      if (res.statusCode !== 200) {
        return reject(new Error(`Download failed with status ${res.statusCode}`));
      }

      const totalBytes = parseInt(res.headers['content-length'], 10) || 0;
      let downloadedBytes = 0;
      const file = fs.createWriteStream(destPath);

      res.on('data', (chunk) => {
        downloadedBytes += chunk.length;
        if (totalBytes > 0 && onProgress) {
          onProgress(Math.round((downloadedBytes / totalBytes) * 100), downloadedBytes, totalBytes);
        }
      });

      res.pipe(file);

      file.on('finish', () => {
        file.close();
        resolve(destPath);
      });

      file.on('error', (err) => {
        fs.unlink(destPath, () => {});
        reject(err);
      });
    });
  });
}

// ============================================================
//  Build the java command args (shared across platforms)
// ============================================================

function buildJavaArgs(config, installDir) {
  const preflight = runPreflight();
  const javaPath = preflight.java.path || 'java';
  const jarPath = path.join(installDir, 'minima.jar');

  let args = [`-jar "${jarPath}"`];

  if (config.port && config.port !== '9001') args.push(`-port ${config.port}`);
  if (config.dataFolder && config.dataFolder !== '~/.minima') args.push(`-data ${config.dataFolder}`);
  if (config.mdsEnable !== false) args.push('-mdsenable');
  if (config.mdsPassword) args.push(`-mdspassword "${config.mdsPassword}"`);
  if (config.rpcEnable) args.push('-rpcenable');
  if (config.rpcPassword) args.push(`-rpcpassword "${config.rpcPassword}"`);
  if (config.desktopMode !== false) args.push('-desktop');
  if (config.noP2P) args.push('-nop2p');
  if (config.connectNode) args.push(`-connect ${config.connectNode}`);
  if (config.dbPassword) args.push(`-dbpassword "${config.dbPassword}"`);
  if (config.archiveMode) args.push('-archive');
  if (config.megaMMR) args.push('-megammr');

  const javaCmd = `"${javaPath}" ${args.join(' ')}`;
  const mdsPort = (parseInt(config.port) || 9001) + 2;

  return { javaPath, jarPath, javaCmd, mdsPort, preflight };
}

// ============================================================
//  macOS: Control Panel (.command), LaunchAgent, .app shortcut
// ============================================================

function generateControlPanelMac(config, installDir) {
  const { javaPath, jarPath, javaCmd, mdsPort, preflight } = buildJavaArgs(config, installDir);
  const tmuxPath = preflight.tmux.path || 'tmux';

  const script = `#!/bin/bash
# ============================================================
#  Minima Node — Control Panel
#  Double-click this file to manage your Minima node.
#  Generated by minima-installer
# ============================================================

JAVA="${javaPath}"
TMUX="${tmuxPath}"
JAR="${jarPath}"
SESSION="minima"
JAVA_CMD='${javaCmd}'
MDS_PORT="${mdsPort}"

# Colors
GREEN='\\033[0;32m'
AMBER='\\033[0;33m'
RED='\\033[0;31m'
BOLD='\\033[1m'
DIM='\\033[2m'
NC='\\033[0m'

is_running() {
  "$TMUX" has-session -t "$SESSION" 2>/dev/null
}

get_status() {
  if is_running; then
    echo -e "\${GREEN}● Running\${NC} \${DIM}(port ${config.port || '9001'})\${NC}"
  else
    echo -e "\${RED}● Stopped\${NC}"
  fi
}

do_start() {
  if is_running; then
    echo ""
    echo -e "  \${AMBER}●\${NC} Minima is already running."
    echo ""
    return
  fi
  echo ""
  echo -e "  Starting Minima..."
  "$TMUX" new-session -d -s "$SESSION" "\$JAVA_CMD; echo ''; echo 'Minima has stopped. Press Enter to close.'; read"
  sleep 2
  if is_running; then
    echo -e "  \${GREEN}✓\${NC} Minima started successfully."
  else
    echo -e "  \${RED}✗\${NC} Minima failed to start. Choose 'View node' to see errors."
  fi
  echo ""
}

do_stop() {
  if ! is_running; then
    echo ""
    echo -e "  \${AMBER}●\${NC} Minima is not running."
    echo ""
    return
  fi
  echo ""
  echo -e "  Stopping Minima..."
  "$TMUX" send-keys -t "$SESSION" "quit" Enter
  sleep 3
  if is_running; then
    "$TMUX" kill-session -t "$SESSION"
  fi
  echo -e "  \${GREEN}✓\${NC} Minima stopped."
  echo ""
}

do_restart() {
  if is_running; then
    do_stop
  fi
  do_start
}

do_view() {
  if ! is_running; then
    echo ""
    echo -e "  \${AMBER}●\${NC} Minima is not running. Start it first."
    echo ""
    return
  fi
  echo ""
  echo -e "  \${DIM}Attaching to tmux session. To come back here:\${NC}"
  echo -e "  \${DIM}Press Ctrl+B then D\${NC}"
  echo ""
  sleep 1
  "$TMUX" attach -t "$SESSION"
}

do_open_mds() {
  echo ""
  echo -e "  Opening MDS Hub at \${BOLD}https://localhost:\$MDS_PORT\${NC}"
  echo -e "  \${DIM}You may see a certificate warning — that's normal.\${NC}"
  echo ""
  open "https://localhost:\$MDS_PORT"
}

# Main menu loop
while true; do
  clear
  echo ""
  echo -e "  \${AMBER}\${BOLD}● Minima Node\${NC}"
  echo -e "  \${DIM}─────────────────────────────────\${NC}"
  echo ""
  echo -e "  Status: $(get_status)"
  echo ""
  echo -e "  \${BOLD}1)\${NC} Start node"
  echo -e "  \${BOLD}2)\${NC} Stop node"
  echo -e "  \${BOLD}3)\${NC} Restart node"
  echo -e "  \${BOLD}4)\${NC} View node (attach tmux)"
  echo -e "  \${BOLD}5)\${NC} Open MDS Hub in browser"
  echo -e "  \${BOLD}6)\${NC} Exit"
  echo ""
  echo -ne "  \${BOLD}Choose [1-6]:\${NC} "
  read -n 1 choice
  echo ""

  case $choice in
    1) do_start ;;
    2) do_stop ;;
    3) do_restart ;;
    4) do_view ;;
    5) do_open_mds ;;
    6) echo ""; echo -e "  \${DIM}Goodbye!\${NC}"; echo ""; exit 0 ;;
    *) echo -e "  \${RED}Invalid choice.\${NC}" ;;
  esac

  if [[ "$choice" != "4" && "$choice" != "6" ]]; then
    echo -e "  \${DIM}Press any key to continue...\${NC}"
    read -n 1 -s
  fi
done
`;

  const scriptPath = path.join(installDir, 'Minima.command');
  fs.writeFileSync(scriptPath, script, { mode: 0o755 });
  return { scriptPath, javaCmd, mdsPort };
}

function generateLaunchAgentMac(installDir, javaCmd) {
  const preflight = runPreflight();
  const tmuxPath = preflight.tmux.path || 'tmux';
  const startScript = path.join(installDir, 'start-minima-daemon.sh');

  const daemonScript = `#!/bin/bash
SESSION="minima"
TMUX="${tmuxPath}"
if "$TMUX" has-session -t "$SESSION" 2>/dev/null; then
  exit 0
fi
"$TMUX" new-session -d -s "$SESSION" '${javaCmd}'
`;
  fs.writeFileSync(startScript, daemonScript, { mode: 0o755 });
  const logPath = path.join(installDir, 'minima-launcher.log');

  const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.minima.node</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>${startScript}</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>StandardOutPath</key>
  <string>${logPath}</string>
  <key>StandardErrorPath</key>
  <string>${logPath}</string>
</dict>
</plist>`;

  const plistDir = path.join(os.homedir(), 'Library', 'LaunchAgents');
  fs.mkdirSync(plistDir, { recursive: true });
  const plistPath = path.join(plistDir, 'com.minima.node.plist');
  fs.writeFileSync(plistPath, plist);
  return plistPath;
}

function createDesktopShortcutMac(installDir) {
  const homeDir = os.homedir();
  const desktopDir = path.join(homeDir, 'Desktop');
  const controlPanel = path.join(installDir, 'Minima.command');

  const appDir = path.join(desktopDir, 'Minima.app');
  const contentsDir = path.join(appDir, 'Contents');
  const macosDir = path.join(contentsDir, 'MacOS');
  const resourcesDir = path.join(contentsDir, 'Resources');

  fs.mkdirSync(macosDir, { recursive: true });
  fs.mkdirSync(resourcesDir, { recursive: true });

  const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleExecutable</key>
  <string>Minima</string>
  <key>CFBundleName</key>
  <string>Minima</string>
  <key>CFBundleIdentifier</key>
  <string>com.minima.control</string>
  <key>CFBundleVersion</key>
  <string>1.0</string>
  <key>CFBundlePackageType</key>
  <string>APPL</string>
  <key>CFBundleIconFile</key>
  <string>minima</string>
  <key>LSUIElement</key>
  <false/>
</dict>
</plist>`;
  fs.writeFileSync(path.join(contentsDir, 'Info.plist'), plist);

  const executable = `#!/bin/bash
open -a Terminal "${controlPanel}"
`;
  fs.writeFileSync(path.join(macosDir, 'Minima'), executable, { mode: 0o755 });

  try {
    const icnsSource = path.join(__dirname, '..', 'assets', 'minima.icns');
    fs.copyFileSync(icnsSource, path.join(resourcesDir, 'minima.icns'));
  } catch {}

  return appDir;
}

function launchTmuxSession(javaCmd) {
  const preflight = runPreflight();
  const tmuxPath = preflight.tmux.path || 'tmux';
  try {
    execSync(`"${tmuxPath}" new-session -d -s minima '${javaCmd}; echo ""; echo "Minima has stopped. Press Enter to close."; read'`, { encoding: 'utf8' });
    execSync(`sleep 2 && "${tmuxPath}" has-session -t minima`, { encoding: 'utf8' });
    return true;
  } catch (err) {
    throw new Error(`Failed to start tmux session: ${err.message}`);
  }
}

// ============================================================
//  Windows: Control Panel (.bat), Startup folder, desktop .bat
// ============================================================

function generateControlPanelWin(config, installDir) {
  const { javaPath, jarPath, javaCmd, mdsPort } = buildJavaArgs(config, installDir);
  const pidFile = path.join(installDir, 'minima.pid');
  const port = config.port || '9001';

  // On Windows, we use javaw for background and save PID via wmic
  // For "view", we start java (not javaw) in a visible window
  const script = `@echo off
setlocal enabledelayedexpansion
title Minima Node - Control Panel

set "JAVA=${javaPath}"
set "JAR=${jarPath}"
set "PIDFILE=${pidFile}"
set "MDS_PORT=${mdsPort}"
set "PORT=${port}"
set JAVA_ARGS=-jar "${jarPath}"${buildWinArgs(config)}

:menu
cls
echo.
echo   * Minima Node
echo   ---------------------------------
echo.

REM Check if running
set "STATUS=Stopped"
set "STATUSCOLOR=[91m"
if exist "%PIDFILE%" (
  set /p PID=<"%PIDFILE%"
  tasklist /FI "PID eq !PID!" /NH 2>nul | find /i "java" >nul
  if !errorlevel! equ 0 (
    set "STATUS=Running (port %PORT%)"
    set "STATUSCOLOR=[92m"
  ) else (
    del "%PIDFILE%" 2>nul
  )
)
echo   Status: !STATUSCOLOR!!STATUS![0m
echo.
echo   1) Start node
echo   2) Stop node
echo   3) Restart node
echo   4) View node (open log window)
echo   5) Open MDS Hub in browser
echo   6) Exit
echo.
set /p "choice=  Choose [1-6]: "

if "%choice%"=="1" goto do_start
if "%choice%"=="2" goto do_stop
if "%choice%"=="3" goto do_restart
if "%choice%"=="4" goto do_view
if "%choice%"=="5" goto do_open_mds
if "%choice%"=="6" goto do_exit
echo   Invalid choice.
pause >nul
goto menu

:do_start
echo.
if exist "%PIDFILE%" (
  set /p PID=<"%PIDFILE%"
  tasklist /FI "PID eq !PID!" /NH 2>nul | find /i "java" >nul
  if !errorlevel! equ 0 (
    echo   * Minima is already running.
    echo.
    pause
    goto menu
  )
)
echo   Starting Minima...
start "Minima Node" /min cmd /c ""%JAVA%" %JAVA_ARGS% ^& echo. ^& echo Minima has stopped. Press any key to close. ^& pause >nul"
REM Wait a moment then find the PID
timeout /t 3 /nobreak >nul
for /f "tokens=2" %%i in ('tasklist /FI "WINDOWTITLE eq Minima Node" /NH 2^>nul ^| find /i "cmd"') do (
  echo %%i> "%PIDFILE%"
)
REM Also try to find java process
for /f "tokens=2" %%i in ('wmic process where "commandline like '%%minima.jar%%'" get processid /value 2^>nul ^| find "="') do (
  echo %%i> "%PIDFILE%"
)
if exist "%PIDFILE%" (
  echo   [92m✓[0m Minima started successfully.
) else (
  echo   [91m✗[0m Minima may have failed to start. Choose 'View node' to check.
)
echo.
pause
goto menu

:do_stop
echo.
if not exist "%PIDFILE%" (
  echo   * Minima is not running.
  echo.
  pause
  goto menu
)
echo   Stopping Minima...
REM Kill all java processes running minima.jar
for /f "tokens=2" %%i in ('wmic process where "commandline like '%%minima.jar%%'" get processid /value 2^>nul ^| find "="') do (
  taskkill /PID %%i /F >nul 2>nul
)
del "%PIDFILE%" 2>nul
echo   [92m✓[0m Minima stopped.
echo.
pause
goto menu

:do_restart
call :do_stop_silent
goto do_start

:do_stop_silent
if not exist "%PIDFILE%" goto :eof
for /f "tokens=2" %%i in ('wmic process where "commandline like '%%minima.jar%%'" get processid /value 2^>nul ^| find "="') do (
  taskkill /PID %%i /F >nul 2>nul
)
del "%PIDFILE%" 2>nul
timeout /t 2 /nobreak >nul
goto :eof

:do_view
echo.
REM Start a visible java window so the user can see output
echo   Opening Minima in a new window...
echo   Close that window to stop the node.
echo.
start "Minima Node" cmd /c ""%JAVA%" %JAVA_ARGS% & echo. & echo Minima has stopped. Press any key to close. & pause >nul"
pause
goto menu

:do_open_mds
echo.
echo   Opening MDS Hub at https://localhost:%MDS_PORT%
echo   You may see a certificate warning - that's normal.
echo.
start https://localhost:%MDS_PORT%
pause
goto menu

:do_exit
echo.
echo   Goodbye!
echo.
exit /b 0
`;

  const scriptPath = path.join(installDir, 'Minima.bat');
  fs.writeFileSync(scriptPath, script);
  return { scriptPath, javaCmd, mdsPort };
}

function buildWinArgs(config) {
  let args = '';
  if (config.port && config.port !== '9001') args += ` -port ${config.port}`;
  if (config.dataFolder && config.dataFolder !== '~/.minima') args += ` -data ${config.dataFolder}`;
  if (config.mdsEnable !== false) args += ' -mdsenable';
  if (config.mdsPassword) args += ` -mdspassword "${config.mdsPassword}"`;
  if (config.rpcEnable) args += ' -rpcenable';
  if (config.rpcPassword) args += ` -rpcpassword "${config.rpcPassword}"`;
  if (config.desktopMode !== false) args += ' -desktop';
  if (config.noP2P) args += ' -nop2p';
  if (config.connectNode) args += ` -connect ${config.connectNode}`;
  if (config.dbPassword) args += ` -dbpassword "${config.dbPassword}"`;
  if (config.archiveMode) args += ' -archive';
  if (config.megaMMR) args += ' -megammr';
  return args;
}

function generateAutoStartWin(installDir, javaCmd) {
  const startupDir = path.join(os.homedir(), 'AppData', 'Roaming', 'Microsoft', 'Windows', 'Start Menu', 'Programs', 'Startup');
  fs.mkdirSync(startupDir, { recursive: true });

  const { javaPath, jarPath } = buildJavaArgs({}, installDir);

  // A small .bat in the Startup folder that launches Minima minimized
  const startupScript = `@echo off
REM Minima Node — Auto-start on login
REM Generated by minima-installer
start "Minima Node" /min cmd /c "${javaCmd}"
`;

  const startupPath = path.join(startupDir, 'Minima.bat');
  fs.writeFileSync(startupPath, startupScript);
  return startupPath;
}

function createDesktopShortcutWin(installDir) {
  const homeDir = os.homedir();
  const desktopDir = path.join(homeDir, 'Desktop');
  const controlPanel = path.join(installDir, 'Minima.bat');

  // Create a small .bat on Desktop that launches the control panel
  const shortcut = `@echo off
cd /d "${installDir}"
call "Minima.bat"
`;
  const shortcutPath = path.join(desktopDir, 'Minima.bat');
  fs.writeFileSync(shortcutPath, shortcut);
  return shortcutPath;
}

function launchMinimaWin(javaCmd, installDir) {
  // Write a small launcher script and execute it — avoids quoting issues with execSync + start
  const launcherPath = path.join(installDir, 'start-minima.bat');
  const launcher = `@echo off\r\nstart "Minima Node" /min cmd /c "${javaCmd}"\r\n`;
  fs.writeFileSync(launcherPath, launcher);

  try {
    spawn('cmd.exe', ['/c', launcherPath], { detached: true, stdio: 'ignore' }).unref();
    return true;
  } catch (err) {
    // Non-fatal — the control panel can start it later
    console.error('Warning: Could not auto-start Minima:', err.message);
    return false;
  }
}

// ============================================================
//  Main install — dispatches to platform-specific functions
// ============================================================

async function install(config, sendEvent) {
  const homeDir = os.homedir();
  const installDir = path.join(homeDir, 'minima-installer');

  sendEvent('status', 'Preparing installation directory...');
  fs.mkdirSync(installDir, { recursive: true });

  sendEvent('status', 'Downloading minima.jar from GitHub...');
  const jarPath = await downloadJar(installDir, (percent, downloaded, total) => {
    const mb = (downloaded / 1024 / 1024).toFixed(1);
    const totalMb = (total / 1024 / 1024).toFixed(1);
    sendEvent('progress', JSON.stringify({ percent, downloaded: mb, total: totalMb }));
  });
  sendEvent('status', 'Download complete.');

  let scriptPath, javaCmd, mdsPort;

  if (isWindows) {
    sendEvent('status', 'Generating Minima control panel...');
    ({ scriptPath, javaCmd, mdsPort } = generateControlPanelWin(config, installDir));

    if (config.autoStart) {
      sendEvent('status', 'Setting up auto-start on login...');
      generateAutoStartWin(installDir, javaCmd);
    }

    sendEvent('status', 'Starting Minima...');
    launchMinimaWin(javaCmd, installDir);

    sendEvent('status', 'Creating desktop shortcut...');
    createDesktopShortcutWin(installDir);
  } else {
    sendEvent('status', 'Generating Minima control panel...');
    ({ scriptPath, javaCmd, mdsPort } = generateControlPanelMac(config, installDir));

    if (config.autoStart) {
      sendEvent('status', 'Setting up auto-start on login...');
      generateLaunchAgentMac(installDir, javaCmd);
    }

    sendEvent('status', 'Starting Minima in tmux session...');
    launchTmuxSession(javaCmd);

    sendEvent('status', 'Creating desktop shortcut...');
    createDesktopShortcutMac(installDir);
  }

  sendEvent('complete', JSON.stringify({
    installDir,
    jarPath,
    controlPanel: scriptPath,
    javaCmd,
    mdsPort,
    tmuxSession: isWindows ? null : 'minima'
  }));
}

module.exports = { install };
