const https = require('https');
const http = require('http');
const fs = require('fs');
const path = require('path');
const { execSync, spawn } = require('child_process');
const { runPreflight } = require('./preflight');

const JAR_URL = 'https://github.com/minima-global/Minima/raw/master/jar/minima.jar';

function followRedirects(url, callback) {
  const proto = url.startsWith('https') ? https : http;
  proto.get(url, { headers: { 'User-Agent': 'minima-installer' } }, (res) => {
    if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
      followRedirects(res.headers.location, callback);
    } else {
      callback(null, res);
    }
  }).on('error', (err) => callback(err));
}

function downloadJar(destDir, onProgress) {
  return new Promise((resolve, reject) => {
    fs.mkdirSync(destDir, { recursive: true });
    const destPath = path.join(destDir, 'minima.jar');

    followRedirects(JAR_URL, (err, res) => {
      if (err) return reject(err);
      if (res.statusCode !== 200) {
        return reject(new Error(`Download failed with status ${res.statusCode}`));
      }

      const totalBytes = parseInt(res.headers['content-length'], 10) || 0;
      let downloadedBytes = 0;
      const file = fs.createWriteStream(destPath);

      res.on('data', (chunk) => {
        downloadedBytes += chunk.length;
        if (totalBytes > 0 && onProgress) {
          onProgress(Math.round((downloadedBytes / totalBytes) * 100), downloadedBytes, totalBytes);
        }
      });

      res.pipe(file);

      file.on('finish', () => {
        file.close();
        resolve(destPath);
      });

      file.on('error', (err) => {
        fs.unlink(destPath, () => {});
        reject(err);
      });
    });
  });
}

function generateControlPanel(config, installDir) {
  const preflight = runPreflight();
  const javaPath = preflight.java.path || 'java';
  const tmuxPath = preflight.tmux.path || 'tmux';
  const jarPath = path.join(installDir, 'minima.jar');

  let args = [`-jar "${jarPath}"`];

  if (config.port && config.port !== '9001') args.push(`-port ${config.port}`);
  if (config.dataFolder && config.dataFolder !== '~/.minima') args.push(`-data ${config.dataFolder}`);
  if (config.mdsEnable !== false) args.push('-mdsenable');
  if (config.mdsPassword) args.push(`-mdspassword "${config.mdsPassword}"`);
  if (config.rpcEnable) args.push('-rpcenable');
  if (config.rpcPassword) args.push(`-rpcpassword "${config.rpcPassword}"`);
  if (config.desktopMode !== false) args.push('-desktop');
  if (config.noP2P) args.push('-nop2p');
  if (config.connectNode) args.push(`-connect ${config.connectNode}`);
  if (config.dbPassword) args.push(`-dbpassword "${config.dbPassword}"`);
  if (config.archiveMode) args.push('-archive');
  if (config.megaMMR) args.push('-megammr');

  const javaCmd = `"${javaPath}" ${args.join(' ')}`;
  const mdsPort = (parseInt(config.port) || 9001) + 2;

  const script = `#!/bin/bash
# ============================================================
#  Minima Node — Control Panel
#  Double-click this file to manage your Minima node.
#  Generated by minima-installer
# ============================================================

JAVA="${javaPath}"
TMUX="${tmuxPath}"
JAR="${jarPath}"
SESSION="minima"
JAVA_CMD='${javaCmd}'
MDS_PORT="${mdsPort}"

# Colors
GREEN='\\033[0;32m'
AMBER='\\033[0;33m'
RED='\\033[0;31m'
BOLD='\\033[1m'
DIM='\\033[2m'
NC='\\033[0m'

is_running() {
  "$TMUX" has-session -t "$SESSION" 2>/dev/null
}

get_status() {
  if is_running; then
    echo -e "\${GREEN}● Running\${NC} \${DIM}(port ${config.port || '9001'})\${NC}"
  else
    echo -e "\${RED}● Stopped\${NC}"
  fi
}

do_start() {
  if is_running; then
    echo ""
    echo -e "  \${AMBER}●\${NC} Minima is already running."
    echo ""
    return
  fi
  echo ""
  echo -e "  Starting Minima..."
  "$TMUX" new-session -d -s "$SESSION" "\$JAVA_CMD; echo ''; echo 'Minima has stopped. Press Enter to close.'; read"
  sleep 2
  if is_running; then
    echo -e "  \${GREEN}✓\${NC} Minima started successfully."
  else
    echo -e "  \${RED}✗\${NC} Minima failed to start. Choose 'View node' to see errors."
  fi
  echo ""
}

do_stop() {
  if ! is_running; then
    echo ""
    echo -e "  \${AMBER}●\${NC} Minima is not running."
    echo ""
    return
  fi
  echo ""
  echo -e "  Stopping Minima..."
  "$TMUX" send-keys -t "$SESSION" "quit" Enter
  sleep 3
  if is_running; then
    "$TMUX" kill-session -t "$SESSION"
  fi
  echo -e "  \${GREEN}✓\${NC} Minima stopped."
  echo ""
}

do_restart() {
  if is_running; then
    do_stop
  fi
  do_start
}

do_view() {
  if ! is_running; then
    echo ""
    echo -e "  \${AMBER}●\${NC} Minima is not running. Start it first."
    echo ""
    return
  fi
  echo ""
  echo -e "  \${DIM}Attaching to tmux session. To come back here:\${NC}"
  echo -e "  \${DIM}Press Ctrl+B then D\${NC}"
  echo ""
  sleep 1
  "$TMUX" attach -t "$SESSION"
}

do_open_mds() {
  echo ""
  echo -e "  Opening MDS Hub at \${BOLD}https://localhost:\$MDS_PORT\${NC}"
  echo -e "  \${DIM}You may see a certificate warning — that's normal.\${NC}"
  echo ""
  open "https://localhost:\$MDS_PORT"
}

# Main menu loop
while true; do
  clear
  echo ""
  echo -e "  \${AMBER}\${BOLD}● Minima Node\${NC}"
  echo -e "  \${DIM}─────────────────────────────────\${NC}"
  echo ""
  echo -e "  Status: $(get_status)"
  echo ""
  echo -e "  \${BOLD}1)\${NC} Start node"
  echo -e "  \${BOLD}2)\${NC} Stop node"
  echo -e "  \${BOLD}3)\${NC} Restart node"
  echo -e "  \${BOLD}4)\${NC} View node (attach tmux)"
  echo -e "  \${BOLD}5)\${NC} Open MDS Hub in browser"
  echo -e "  \${BOLD}6)\${NC} Exit"
  echo ""
  echo -ne "  \${BOLD}Choose [1-6]:\${NC} "
  read -n 1 choice
  echo ""

  case $choice in
    1) do_start ;;
    2) do_stop ;;
    3) do_restart ;;
    4) do_view ;;
    5) do_open_mds ;;
    6) echo ""; echo -e "  \${DIM}Goodbye!\${NC}"; echo ""; exit 0 ;;
    *) echo -e "  \${RED}Invalid choice.\${NC}" ;;
  esac

  if [[ "$choice" != "4" && "$choice" != "6" ]]; then
    echo -e "  \${DIM}Press any key to continue...\${NC}"
    read -n 1 -s
  fi
done
`;

  const scriptPath = path.join(installDir, 'Minima.command');
  fs.writeFileSync(scriptPath, script, { mode: 0o755 });
  return { scriptPath, javaCmd, mdsPort };
}

function generateLaunchAgent(installDir, javaCmd) {
  // LaunchAgent needs a simple start-only script (no interactive menu)
  const startScript = path.join(installDir, 'start-minima-daemon.sh');
  const preflight = runPreflight();
  const tmuxPath = preflight.tmux.path || 'tmux';

  const daemonScript = `#!/bin/bash
SESSION="minima"
TMUX="${tmuxPath}"
if "$TMUX" has-session -t "$SESSION" 2>/dev/null; then
  exit 0
fi
"$TMUX" new-session -d -s "$SESSION" '${javaCmd}'
`;
  fs.writeFileSync(startScript, daemonScript, { mode: 0o755 });
  const logPath = path.join(installDir, 'minima-launcher.log');

  const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.minima.node</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>${startScript}</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>StandardOutPath</key>
  <string>${logPath}</string>
  <key>StandardErrorPath</key>
  <string>${logPath}</string>
</dict>
</plist>`;

  const plistDir = path.join(process.env.HOME, 'Library', 'LaunchAgents');
  fs.mkdirSync(plistDir, { recursive: true });
  const plistPath = path.join(plistDir, 'com.minima.node.plist');
  fs.writeFileSync(plistPath, plist);
  return plistPath;
}

function createDesktopShortcut(installDir) {
  const homeDir = process.env.HOME;
  const desktopDir = path.join(homeDir, 'Desktop');
  const controlPanel = path.join(installDir, 'Minima.command');

  // Create a minimal .app bundle — this can live on Desktop AND be dragged to the Dock
  const appDir = path.join(desktopDir, 'Minima.app');
  const contentsDir = path.join(appDir, 'Contents');
  const macosDir = path.join(contentsDir, 'MacOS');
  const resourcesDir = path.join(contentsDir, 'Resources');

  fs.mkdirSync(macosDir, { recursive: true });
  fs.mkdirSync(resourcesDir, { recursive: true });

  // Info.plist
  const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleExecutable</key>
  <string>Minima</string>
  <key>CFBundleName</key>
  <string>Minima</string>
  <key>CFBundleIdentifier</key>
  <string>com.minima.control</string>
  <key>CFBundleVersion</key>
  <string>1.0</string>
  <key>CFBundlePackageType</key>
  <string>APPL</string>
  <key>CFBundleIconFile</key>
  <string>minima</string>
  <key>LSUIElement</key>
  <false/>
</dict>
</plist>`;
  fs.writeFileSync(path.join(contentsDir, 'Info.plist'), plist);

  // Executable — opens the .command file in Terminal
  const executable = `#!/bin/bash
open -a Terminal "${controlPanel}"
`;
  const execPath = path.join(macosDir, 'Minima');
  fs.writeFileSync(execPath, executable, { mode: 0o755 });

  // Copy the Minima icon into the app bundle
  try {
    const icnsSource = path.join(__dirname, '..', 'assets', 'minima.icns');
    const icnsDest = path.join(resourcesDir, 'minima.icns');
    fs.copyFileSync(icnsSource, icnsDest);
  } catch {}

  return appDir;
}

function launchTmuxSession(javaCmd) {
  const preflight = runPreflight();
  const tmuxPath = preflight.tmux.path || 'tmux';
  try {
    // Launch directly — no intermediate script needed
    execSync(`"${tmuxPath}" new-session -d -s minima '${javaCmd}; echo ""; echo "Minima has stopped. Press Enter to close."; read'`, { encoding: 'utf8' });
    // Verify it started
    execSync(`sleep 2 && "${tmuxPath}" has-session -t minima`, { encoding: 'utf8' });
    return true;
  } catch (err) {
    throw new Error(`Failed to start tmux session: ${err.message}`);
  }
}

async function install(config, sendEvent) {
  const homeDir = process.env.HOME;
  const installDir = path.join(homeDir, 'minima-installer');

  sendEvent('status', 'Preparing installation directory...');
  fs.mkdirSync(installDir, { recursive: true });

  sendEvent('status', 'Downloading minima.jar from GitHub...');
  const jarPath = await downloadJar(installDir, (percent, downloaded, total) => {
    const mb = (downloaded / 1024 / 1024).toFixed(1);
    const totalMb = (total / 1024 / 1024).toFixed(1);
    sendEvent('progress', JSON.stringify({ percent, downloaded: mb, total: totalMb }));
  });
  sendEvent('status', 'Download complete.');

  sendEvent('status', 'Generating Minima control panel...');
  const { scriptPath, javaCmd, mdsPort } = generateControlPanel(config, installDir);

  let plistPath = null;
  if (config.autoStart) {
    sendEvent('status', 'Setting up auto-start on login...');
    plistPath = generateLaunchAgent(installDir, javaCmd);
  }

  sendEvent('status', 'Starting Minima in tmux session...');
  launchTmuxSession(javaCmd);

  sendEvent('status', 'Creating desktop shortcut...');
  createDesktopShortcut(installDir);

  sendEvent('complete', JSON.stringify({
    installDir,
    jarPath,
    controlPanel: scriptPath,
    plistPath,
    javaCmd,
    mdsPort,
    tmuxSession: 'minima'
  }));
}

module.exports = { install };
